name: geo_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - geopandas
  - matplotlib
  - pandas
  - numpy
  - scikit-learn
  - folium
  - xarray
  - jupyterlab-git 
  - seaborn        
  - pip
  - pip:
      - netcdf4
