name: Build Binder Environment

on:
  push:
    branches:
      - main  # or whatever your default branch is

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build and cache Binder image
        uses: jupyterhub/repo2docker-action@master
        with:
          BINDER_CACHE: true
