name: Build Binder Environment

on:
  push:
    branches:
      - main  # Change if your default branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build and cache Binder image
        uses: machine-learning-apps/repo2docker-action@master
        with:
          MYBINDERORG_CACHE: true
