name: Prebuild Binder image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install repo2docker
        run: pip install jupyter-repo2docker

      - name: Build Binder image without running it
        run: jupyter-repo2docker --no-run --json-logs .
