name: Build Binder Cache Only

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build and cache Binder image (without pushing)
        uses: jupyterhub/repo2docker-action@master
        with:
          BINDER_CACHE: true
          NO_PUSH: true

